export const players = [
  {
    name: "KARIM BENZEMA",
    team: "REAL MADRID CF",
    age: 34,
    position: "ST",
    nationality: "FR",
  },
  {
    name: "LIONEL MESSI",
    team: "PARIS SAINT-GERMAIN",
    age: 34,
    position: "RW",
    nationality: "AR",
  },
  {
    name: "ROBERT LEWANDOWSKI",
    team: "FC BAYERN MUNICH",
    age: 32,
    position: "ST",
    nationality: "PL",
  },
  {
    name: "LIONEL MESSI",
    team: "FC BARCELONA",
    age: 32,
    position: "RW",
    nationality: "AR",
  },
  {
    name: "LUKA MODRIC",
    team: "REAL MADRID CF",
    age: 33,
    position: "CM",
    nationality: "HR",
  },
  {
    name: "CRISTIANO RONALDO",
    team: "REAL MADRID CF",
    age: 32,
    position: "LW",
    nationality: "PT",
  },
  {
    name: "CRISTIANO RONALDO",
    team: "REAL MADRID CF",
    age: 31,
    position: "LW",
    nationality: "PT",
  },
  {
    name: "LIONEL MESSI",
    team: "FC BARCELONA",
    age: 28,
    position: "RW",
    nationality: "AR",
  },
  {
    name: "CRISTIANO RONALDO",
    team: "REAL MADRID CF",
    age: 29,
    position: "LW",
    nationality: "PT",
  },
  {
    name: "CRISTIANO RONALDO",
    team: "REAL MADRID CF",
    age: 28,
    position: "LW",
    nationality: "PT",
  },
  {
    name: "LIONEL MESSI",
    team: "FC BARCELONA",
    age: 25,
    position: "RW",
    nationality: "AR",
  },
  {
    name: "LIONEL MESSI",
    team: "FC BARCELONA",
    age: 24,
    position: "RW",
    nationality: "AR",
  },
  {
    name: "LIONEL MESSI",
    team: "FC BARCELONA",
    age: 23,
    position: "RW",
    nationality: "AR",
  },
  {
    name: "LIONEL MESSI",
    team: "FC BARCELONA",
    age: 22,
    position: "RW",
    nationality: "AR",
  },
  {
    name: "CRISTIANO RONALDO",
    team: "MANCHESTER UNITED",
    age: 23,
    position: "LW",
    nationality: "PT",
  },
  {
    name: "KAKÁ",
    team: "AC MILAN",
    age: 25,
    position: "CAM",
    nationality: "BR",
  },
  {
    name: "FABIO CANNAVARO",
    team: "REAL MADRID CF",
    age: 33,
    position: "CB",
    nationality: "IT",
  },
  {
    name: "RONALDINHO",
    team: "FC BARCELONA",
    age: 25,
    position: "LW",
    nationality: "BR",
  },
  {
    name: "ANDRIY SHEVCHENKO",
    team: "AC MILAN",
    age: 28,
    position: "ST",
    nationality: "UA",
  },
  {
    name: "PAVEL NEDVED",
    team: "JUVENTUS FC",
    age: 31,
    position: "LM",
    nationality: "CZ",
  },
  {
    name: "RONALDO",
    team: "REAL MADRID CF",
    age: 26,
    position: "ST",
    nationality: "BR",
  },
  {
    name: "MICHAEL OWEN",
    team: "LIVERPOOL FC",
    age: 22,
    position: "ST",
    nationality: "GB",
  },
  {
    name: "LUIS FIGO",
    team: "REAL MADRID CF",
    age: 28,
    position: "RM",
    nationality: "PT",
  },
  {
    name: "RIVALDO",
    team: "FC BARCELONA",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "ZINEDINE ZIDANE",
    team: "JUVENTUS FC",
    age: 0,
    position: "",
    nationality: "",
  },
  { name: "RONALDO", team: "INTER", age: 0, position: "", nationality: "" },
  {
    name: "MATTHIAS SAMMER",
    team: "Borussia Dortmund",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "GEORGE WEAH",
    team: "AC MILAN",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "HRISTO STOICHKOV",
    team: "FC BARCELONA",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "ROBERTO BAGGIO",
    team: "JUVENTUS FC",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "MARCO VAN BASTEN",
    team: "AC MILAN",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "JEAN-PIERRE PAPIN",
    team: "MARSEILLE",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "LOTHAR MATTHÄUS",
    team: "INTER MILAN",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "MARCO VAN BASTEN",
    team: "AC MILAN",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "MARCO VAN BASTEN",
    team: "AC MILAN",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "RUUD GULLIT",
    team: "AC MILAN",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "IGOR BELANOV",
    team: "DYNAMO KIEV",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "MICHEL PLATINI",
    team: "JUVENTUS FC",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "MICHEL PLATINI",
    team: "JUVENTUS FC",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "MICHEL PLATINI",
    team: "JUVENTUS FC",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "PAOLO ROSSI",
    team: "JUVENTUS FC",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "KARL-HEINZ RUMMENIGGE",
    team: "FC BAYERN MUNICH",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "KARL-HEINZ RUMMENIGGE",
    team: "FC BAYERN MUNICH",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "KEVIN KEEGAN",
    team: "HAMBURGER SV",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "KEVIN KEEGAN",
    team: "HAMBURGER SV",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "ALLAN SIMONSEN",
    team: "Borussia Mönchengladbach",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "FRANZ BECKENBAUER",
    team: "FC BAYERN MUNICH",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "OLEG BLOKHIN",
    team: "DYNAMO KYEV",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "JOHAN CRUYFF",
    team: "FC BARCELONA",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "JOHAN CRUYFF",
    team: "FC BARCELONA",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "FRANZ BECKENBAUER",
    team: "FC BAYERN MUNICH",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "JOHAN CRUYFF",
    team: "AFC AJAX",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "GERD MÜLLER",
    team: "FC BAYERN MUNICH",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "GIANNI RIVERA",
    team: "AC MILAN",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "GEORGE BEST",
    team: "MANCHESTER UNITED",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "FLÓRIÁN ALBER",
    team: "FERENCVÁROS",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "BOBBY CHARLTON",
    team: "MANCHESTER UNITED",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "EUSÉBIO",
    team: "SL BENFICA",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "DENIS LAW",
    team: "MANCHESTER UNITED",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "LEV YASHIN",
    team: "DYNAMO MOSCOW",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "JOSEF MASOPUST",
    team: "DUKLA PRAGUE",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "OMAR SÍVORI",
    team: "JUVENTUS FC",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "LUIS SUÁREZ",
    team: "FC BARCELONA",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "ALFREDO DI STÉFANO",
    team: "REAL MADRID CF",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "RAYMOND KOPA",
    team: "REAL MADRID CF",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "ALFREDO DI STÉFANO",
    team: "REAL MADRID CF",
    age: 0,
    position: "",
    nationality: "",
  },
  {
    name: "STANLEY MATTHEWS",
    team: "BLACKPOOL",
    age: 0,
    position: "",
    nationality: "",
  },
];
