export const players = [
  {
    year: 2022,
    name: "Karim Benzema",
    club: "Real Madrid",
    age: 34,
    country: "FR",
    position: "ST",
  },
  {
    year: 2021,
    name: "Lionel Messi",
    club: "Paris Saint-Germain",
    age: 34,
    country: "AR",
    position: "RW",
  },
  {
    year: 2020,
    name: "Robert Lewandowski",
    club: "Bayern Munich",
    age: 32,
    country: "PL",
    position: "ST",
  },
  {
    year: 2019,
    name: "Lionel Messi",
    club: "Barcelona",
    age: 32,
    country: "AR",
    position: "RW",
  },
  {
    year: 2018,
    name: "Luka Modrić",
    club: "Real Madrid",
    age: 33,
    country: "HR",
    position: "CM",
  },
  {
    year: 2017,
    name: "Cristiano Ronaldo",
    club: "Real Madrid",
    age: 32,
    country: "PT",
    position: "LW",
  },
  {
    year: 2016,
    name: "Cristiano Ronaldo",
    club: "Real Madrid",
    age: 31,
    country: "PT",
    position: "LW",
  },
  {
    year: 2015,
    name: "Lionel Messi",
    club: "Barcelona",
    age: 28,
    country: "AR",
    position: "RW",
  },
  {
    year: 2014,
    name: "Cristiano Ronaldo",
    club: "Real Madrid",
    age: 29,
    country: "PT",
    position: "LW",
  },
  {
    year: 2013,
    name: "Cristiano Ronaldo",
    club: "Real Madrid",
    age: 28,
    country: "PT",
    position: "LW",
  },
  {
    year: 2012,
    name: "Lionel Messi",
    club: "Barcelona",
    age: 25,
    country: "AR",
    position: "RW",
  },
  {
    year: 2011,
    name: "Lionel Messi",
    club: "Barcelona",
    age: 24,
    country: "AR",
    position: "RW",
  },
  {
    year: 2010,
    name: "Lionel Messi",
    club: "Barcelona",
    age: 23,
    country: "AR",
    position: "RW",
  },
  {
    year: 2009,
    name: "Lionel Messi",
    club: "Barcelona",
    age: 22,
    country: "AR",
    position: "RW",
  },
  {
    year: 2008,
    name: "Cristiano Ronaldo",
    club: "Manchester United",
    age: 23,
    country: "PT",
    position: "LW",
  },
  {
    year: 2007,
    name: "Kaká",
    club: "AC Milan",
    age: 25,
    country: "BR",
    position: "CAM",
  },
  {
    year: 2006,
    name: "Fabio Cannavaro",
    club: "Real Madrid",
    age: 33,
    country: "IT",
    position: "CB",
  },
  {
    year: 2005,
    name: "Ronaldinho",
    club: "Barcelona",
    age: 25,
    country: "BR",
    position: "LW",
  },
  {
    year: 2004,
    name: "Andriy Shevchenko",
    club: "AC Milan",
    age: 28,
    country: "Ukraine",
    position: "ST",
  },
  {
    year: 2003,
    name: "Pavel Nedvěd",
    club: "Juventus",
    age: 31,
    country: "CZ",
    position: "LM",
  },
  {
    year: 2002,
    name: "Ronaldo",
    club: "Real Madrid",
    age: 26,
    country: "BR",
    position: "ST",
  },
  {
    year: 2001,
    name: "Michael Owen",
    club: "Liverpool",
    age: 22,
    country: "GB",
    position: "RW",
  },
  {
    year: 2000,
    name: "Luis Figo",
    club: "Real Madrid",
    age: 28,
    country: "PT",
    position: "RM",
  },
  {
    year: 1999,
    name: "Rivaldo",
    club: "FC Barcelona",
    age: 27,
    country: "BR",
    position: "LW",
  },
  {
    year: 1998,
    name: "Zinedine Zidane",
    club: "Juventus",
    age: 26,
    country: "FR",
    position: "CAM",
  },
  {
    year: 1997,
    name: "Ronaldo",
    club: "Inter Milan",
    age: 21,
    country: "BR",
    position: "ST",
  },
  {
    year: 1996,
    name: "Matthias Sammer",
    club: "Borussia Dortmund",
    age: 29,
    country: "DE",
    position: "CB",
  },
  {
    year: 1995,
    name: "George Weah",
    club: "AC Milan",
    age: 29,
    country: "LR",
    position: "RW",
  },
  {
    year: 1994,
    name: "Hristo Stoichkov",
    club: "FC Barcelona",
    age: 28,
    country: "BG",
    position: "LW",
  },
  {
    year: 1993,
    name: "Roberto Baggio",
    club: "Juventus",
    age: 26,
    country: "IT",
    position: "CF",
  },
  {
    year: 1992,
    name: "Marco van Basten",
    club: "AC Milan",
    age: 28,
    country: "NL",
    position: "ST",
  },
  {
    year: 1991,
    name: "Jean-Pierre Papin",
    club: "Olympique Marseille",
    age: 28,
    country: "FR",
    position: "ST",
  },
  {
    year: 1990,
    name: "Lothar Matthäus",
    club: "Inter Milan",
    age: 29,
    country: "DE",
    position: "CM",
  },
  {
    year: 1989,
    name: "Marco van Basten",
    country: "NL",
    club: "AC Milan",
    position: "ST",
    age: 24,
  },
  {
    year: 1988,
    name: "Marco van Basten",
    country: "NL",
    club: "AC Milan",
    position: "ST",
    age: 23,
  },
  {
    year: 1987,
    name: "Ruud Gullit",
    country: "NL",
    club: "AC Milan",
    position: "CF",
    age: 25,
  },
  {
    year: 1986,
    name: "Igor Belanov",
    country: "UA",
    club: "Dynamo Kyiv",
    position: "ST",
    age: 25,
  },
  {
    year: 1985,
    name: "Michel Platini",
    country: "FR",
    club: "Juventus",
    position: "CAM",
    age: 30,
  },
  {
    year: 1984,
    name: "Michel Platini",
    country: "FR",
    club: "Juventus",
    position: "CAM",
    age: 29,
  },
  {
    year: 1983,
    name: "Michel Platini",
    country: "FR",
    club: "Juventus",
    position: "CAM",
    age: 28,
  },
  {
    year: 1982,
    name: "Paolo Rossi",
    country: "IT",
    club: "Juventus",
    position: "ST",
    age: 26,
  },
  {
    year: 1981,
    name: "Karl-Heinz Rummenigge",
    country: "DE",
    club: "Bayern Munich",
    position: "ST",
    age: 26,
  },
  {
    year: 1980,
    name: "Karl-Heinz Rummenigge",
    country: "DE",
    club: "Bayern Munich",
    position: "ST",
    age: 25,
  },
  {
    year: 1979,
    name: "Kevin Keegan",
    position: "ST",
    country: "GB",
    club: "Hamburg",
    age: 28,
  },
  {
    year: 1978,
    name: "Kevin Keegan",
    position: "ST",
    country: "GB",
    club: "Hamburg",
    age: 27,
  },
  {
    year: 1977,
    name: "Allan Simonsen",
    position: "RW",
    country: "DK",
    club: "Borussia Mönchengladbach",
    age: 25,
  },
  {
    year: 1976,
    name: "Franz Beckenbauer",
    position: "CB",
    country: "DE",
    club: "Bayern Munich",
    age: 31,
  },
  {
    year: 1975,
    name: "Oleg Blokhin",
    position: "LW",
    country: "UA",
    club: "Dynamo Kiev",
    age: 23,
  },
  {
    year: 1974,
    name: "Johan Cruyff",
    position: "CAM",
    country: "NL",
    club: "Barcelona",
    age: 27,
  },
  {
    year: 1973,
    name: "Johan Cruyff",
    position: "CAM",
    country: "NL",
    club: "Barcelona",
    age: 26,
  },
  {
    year: 1972,
    name: "Franz Beckenbauer",
    position: "CB",
    country: "DE",
    club: "Bayern Munich",
    age: 27,
  },
  {
    year: 1971,
    name: "Johan Cruyff",
    position: "CAM",
    country: "NL",
    club: "Ajax",
    age: 24,
  },
  {
    year: 1970,
    name: "Gerd Muller",
    position: "ST",
    country: "DE",
    club: "Bayern Munich",
    age: 24,
  },
  {
    year: 1969,
    name: "Gianni Rivera",
    club: "AC Milan",
    country: "IT",
    age: 26,
    position: "CAM",
  },
  {
    year: 1968,
    name: "George Best",
    club: "Manchester United",
    country: "GB",
    age: 22,
    position: "LW",
  },
  {
    year: 1967,
    name: "Florian Albert",
    club: "Ferencváros",
    country: "HU",
    age: 24,
    position: "ST",
  },
  {
    year: 1966,
    name: "Bobby Charlton",
    club: "Manchester United",
    country: "GB",
    age: 28,
    position: "CAM",
  },
  {
    year: 1965,
    name: "Eusébio",
    club: "Benfica",
    country: "PT",
    age: 23,
    position: "ST",
  },
  {
    year: 1964,
    name: "Denis Law",
    club: "Manchester United",
    country: "GB",
    age: 24,
    position: "ST",
  },
  {
    year: 1963,
    name: "Lev Yashin",
    club: "Dynamo Moscow",
    country: "RU",
    age: 34,
    position: "GK",
  },
  {
    year: 1962,
    name: "Josef Masopust",
    club: "Dukla Prague",
    country: "CZ",
    age: 31,
    position: "CM",
  },
  {
    year: 1961,
    name: "Omar Sívori",
    club: "Juventus",
    country: "AR",
    age: 26,
    position: "CF",
  },
  {
    year: 1960,
    name: "Luis Suárez",
    club: "Barcelona",
    country: "ES",
    age: 25,
    position: "CM",
  },
  {
    year: 1959,
    name: "Alfredo Di Stefano",
    club: "Real Madrid",
    country: "AR",
    age: 32,
    position: "CF",
  },
  {
    year: 1958,
    name: "Raymond Kopa",
    club: "Real Madrid",
    country: "FR",
    age: 26,
    position: "RW",
  },
  {
    year: 1957,
    name: "Alfredo Di Stefano",
    club: "Real Madrid",
    country: "AR",
    age: 31,
    position: "CF",
  },
  {
    year: 1956,
    name: "Stanley Matthews",
    club: "Blackpool",
    country: "GB",
    age: 41,
    position: "RW",
  },
];
